apiVersion: apps/v1
kind: Deployment
metadata:
    name: order-service
    namespace: polar
    labels:
        app: order-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: order-service
    template:
        metadata:
            name: order-service
            labels:
                app: order-service
        spec:
            containers:
                -   name: order-service
                    image: order-service
                    imagePullPolicy: IfNotPresent
                    lifecycle:
                        preStop:
                            exec:
                                command: [ "sh", "-c", "sleep 5" ]
                    ports:
                        -   containerPort: 9002
                    env:
                        -   name: BPL_JVM_THREAD_COUNT
                            value: "50"
                        -   name: BPL_DEBUG_ENABLED
                            value: "true"
                        -   name: BPL_DEBUG_PORT
                            value: "8002"
                        -   name: POLAR_CATALOG_SERVICE_URI
                            value: http://catalog-service
                        -   name: SPRING_CLOUD_CONFIG_URI
                            value: http://config-service
                        -   name: SPRING_R2DBC_URL
                            value: r2dbc:postgresql://polar-postgres:5432/polardb_order
                        -   name: SPRING_FLYWAY_URL
                            value: jdbc:postgresql://polar-postgres:5432/polardb_order
                        -   name: SPRING_RABBITMQ_HOST
                            value: polar-rabbitmq
                        -   name: SPRING_CLOUD_CONFIG_FAIL-FAST
                            value: "true"
                        -   name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
                            value: http://polar-keycloak/realms/PolarBookshop